vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    articles:
      uri_prefix: /images/articles
      upload_destination: '%kernel.project_dir%/public/images/articles'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    attachment:
      uri_prefix: /images/attachment
      upload_destination: '%kernel.project_dir%/public/images/attachment'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    avatar:
      uri_prefix: /images/avatar
      upload_destination: '%kernel.project_dir%/public/images/avatar'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

