vich_uploader:
  db_driver: orm
  metadata:
    type: annotation
  mappings:
    articles:
      uri_prefix: /images/articles
      upload_destination: '%kernel.project_dir%/public/images/articles'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

