version: '3'

services:
###> doctrine/doctrine-bundle ###
    nginx: 
      image: nginx
      volumes:
        - ./:/var/www/symfony 
        - ./docker/nginx/conf.d:/etc/nginx/conf.d
      ports:
        - 8082:80
      depends_on: 
        - php-fpm

    php-fpm:
      build: ./docker/php-fpm
      depends_on:
        -  mysql
      volumes: 
        - ./:/var/www/symfony
        - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      links:
        - typesense

    mysql:
      image: mariadb:10.1
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ebuy
        MYSQL_USER: ebuy
        MYSQL_PASSWORD: ebuy
      ports:
        - 3306:3306

    node:
      build: ./docker/node
      command: pnpm run dev
      working_dir: /var/www/symfony/assets
      volumes:
        - ./:/var/www/symfony/assets
      ports:
        - 3000:3000
      depends_on: 
        - php-fpm

    typesense:
      image: typesense/typesense:0.25.1
      volumes: 
        - search-data:/data
      ports:
        - 8108:8108
      command: '--data-dir /data --api-key=typesensekey --enable-cors'

#   database:
#     image: postgres:${POSTGRES_VERSION:-15}-alpine
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB:-app}
#       # You should definitely change the password in production
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#       POSTGRES_USER: ${POSTGRES_USER:-app}
#     volumes:
#       - database_data:/var/lib/postgresql/data:rw
#       # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#       # - ./docker/db/data:/var/lib/postgresql/data:rw
# ###< doctrine/doctrine-bundle ###
volumes:
  search-data:
    driver: local