# app/config/route/liip_imagine.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
# config/routes.yaml
app_logout:
    path: /logout
    methods: GET

controllers:
    resource: ../src/Http/
    type: attribute